<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Kartodromo.Comum</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Recursos\*.png" />
  </ItemGroup>
</Project>
