<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Kartodromo.Recepcao</RootNamespace>
    <AssemblyName>Kartodromo.Recepcao</AssemblyName>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kartodromo.Comum\Kartodromo.Comum.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <EmbeddedResource Include="Icones/*.png" />
  </ItemGroup>
</Project>
